export enum ECharacterBonusAttribute {
  CRIT_DMG = 'crit-dmg',
  ELEMENTAL_MASTERY = 'elemental-mastery',
  ENERGY_RECHARGE = 'energy-recharge',
  CRIT_RATE = 'crit-rate',
  HP = 'hp',
  HEALING_BONUS = 'healing-bonus',
  PHYSICAL_DMG_BONUS = 'physical-dmg-bonus',
  ATK = 'atk',
  DEF = 'def',
  PYRO_DMG_BONUS = 'pyro-dmg-bonus',
  HYDRO_DMG_BONUS = 'hydro-dmg-bonus',
  DENDRO_DMG_BONUS = 'dendro-dmg-bonus',
  ELECTRO_DMG_BONUS = 'electro-dmg-bonus',
  CRYO_DMG_BONUS = 'cryo-dmg-bonus',
  ANEMO_DMG_BONUS = 'anemo-dmg-bonus',
  GEO_DMG_BONUS = 'geo-dmg-bonus',
  OTHER = 'other',
}
